### PR TITLE
Allows custom cloning strategies and custom action loaders while maintaining backwards compatibility

### PR DESCRIPTION
**Pull request by caiobalthazar**
This PR allows custom cloning strategies and custom actions loaders while maintaining backward compatibility.
This is useful when we have complex stores with enhancers such as [redux-saga](https://github.com/yelouafi/redux-saga), and we need to customize the cloning strategy in order to support/ignore those.
Also, having a custom action loader function allows for using this tool together with other test tools such as [redux-action-loggin](https://www.npmjs.com/package/redux-action-logging) without duplicating state.
All tests passed.

### CODE REVIEW

**Comment by davidkpiano** [comment]
Thanks, @caiobalthazar! I haven't intended on publicizing this repo, as it is used internally for React-Redux-Form, but if you find it useful, would you like to be a collaborator?

**Comment by caiobalthazar** [comment]
Sure, no problem. 
Also, would it be possible update to npm? ;)

**Comment by davidkpiano** [comment]
Published as 0.5.0!

**Comment by caiobalthazar** [comment]
Thank you @davidkpiano!

**Pull request merged**
